$filesToDelete = @(
    "ADSENSE_READINESS_FORENSIC_AUDIT.md",
    "DEPENDENCY_SECURITY_MATRIX.md",
    "FINAL_SECURITY_RELEASE_GATE.md",
    "GLOBAL_CHANAKYA_COLOR_SYSTEM_REDESIGN_REPORT.md",
    "GLOBAL_CHANAKYA_EDITORIAL_THEME_REDESIGN_REPORT.md",
    "LEGACY_INTELLIGENCE_FRONTEND_CLEANUP_REPORT.md",
    "LINKED_ENTITIES_COMPLETE_REMOVAL_REPORT.md",
    "LINKED_ENTITIES_FINAL_INTEGRITY_CHECK.md",
    "SECURITY_DPDP_SECOND_PASS_VALIDATION.md",
    "SECURITY_HARDENING_IMPLEMENTATION_REPORT.md",
    "SECURITY_P0_P1_REMEDIATION_REPORT.md",
    "api_dump.txt",
    "build-report.md",
    "error-report.md",
    "phase7_1_render_migration_audit.md",
    "schema_auto_generation_implementation_report.md",
    "seo_phase5b_change_manifest.json",
    "seo_phase5b_content_backup.json",
    "seo_phase5b_internal_link_candidates.json",
    "seo_phase5b_prewrite_content_backup.json",
    "seo_phase5c_metadata_baseline.json",
    "seo_schema_full_audit.json",
    "seo_schema_full_verification_report.md",
    "tmp_old_WriteArticleClient.tsx",
    "lighthouse-desktop.json",
    "lighthouse-mobile.json",
    "pagespeed.json",
    
    "apps/web/FINAL_REAL_WORLD_VALIDATION.md",
    "apps/web/STRICT_AUDIT_REPORT.json",
    "apps/web/audit-report.json",
    "apps/web/content-entity-backfill-execution-report.md",
    "apps/web/lighthouse-desktop.json",
    "apps/web/lighthouse-report.json",
    "apps/web/lint-errors.txt",
    "apps/web/local-test-log.txt",
    "apps/web/migration-backup-1787668554107.json",
    "apps/web/migration-backup-1787668725392.json",
    "apps/web/orphan-linking-execution-report.md",
    "apps/web/orphan-linking-final-verification.md",
    "apps/web/phase6_2_forensic_audit.md",
    "apps/web/production-readiness-final.md",
    "apps/web/published_blog_urls.txt",
    "apps/web/tsc-errors.txt",
    "apps/web/validation_data.json",
    "apps/web/server.err",
    "apps/web/server.log",
    "apps/web/temp.html",
    "apps/web/temp_error_page.html",
    "apps/web/temp_page.html",
    "apps/web/tmp_old_WriteArticleClient.tsx",

    "apps/web/scripts/entity-audit-report.md",
    "apps/web/scripts/entity-backfill-approved.json",
    "apps/web/scripts/entity-backfill-execution-report.json",
    "apps/web/scripts/entity-backfill-rejected.json",
    "apps/web/scripts/entity-backfill-review.json",
    "apps/web/scripts/entity-backfill-rollback-manifest.json",
    "apps/web/scripts/entity-backfill-suggestions.json",
    "apps/web/scripts/final-seo-blocker-resolution.json",
    "apps/web/scripts/final-seo-blocker-resolution.md",
    "apps/web/scripts/gsc-top4-backup.json",
    "apps/web/scripts/gsc-top4-implementation-log.json",
    "apps/web/scripts/gsc-top4-implementation-report.json",
    "apps/web/scripts/gsc-top4-measurement-baseline.json",
    "apps/web/scripts/gsc-top4-verification-raw.json",
    "apps/web/scripts/gsc-top5-forensic-report.json",
    "apps/web/scripts/gsc-top5-forensic.json",
    "apps/web/scripts/image-candidate-report.json",
    "apps/web/scripts/orphan-linking-execution-report.json",
    "apps/web/scripts/orphan-linking-final-verification.json",
    "apps/web/scripts/orphan-linking-plan.json",
    "apps/web/scripts/production-readiness-final.json",
    "apps/web/scripts/qa-report.json",
    "apps/web/scripts/semantic-link-investigation.json",
    "apps/web/scripts/semantic-link-investigation.md",
    
    "apps/web/seo_phase2_cleanup_execution_report.md",
    "apps/web/seo_phase2_final_consistency_report.md",
    "apps/web/seo_phase2_final_mapping_validation.md",
    "apps/web/seo_phase2_final_reconciliation_report.md",
    "apps/web/seo_phase2_malformed_entity_cleanup_report.md",
    "apps/web/seo_phase2_ontology_correction_report.md",
    "apps/web/seo_phase2_post_migration_integrity_report.md",
    "apps/web/seo_phase2_pre_migration_backup_report.md",
    "apps/web/seo_phase2_production_migration_report.md",
    "apps/web/seo_phase3_baseline.md",
    "apps/web/seo_phase4_article_scores.csv",
    "apps/web/seo_phase4a_change_manifest.json",
    "apps/web/seo_phase4a_conflict_revalidation.md",

    "apps/backups/affected-blogs-backup-1787639240845.json",
    "apps/scratch/blog_backup_1787207355066.jsonl",
    "backups/blogs_2026-06-30T04-46-31-678Z.json",
    "backups/bookmarks_2026-06-30T04-46-31-678Z.json",
    "backups/likes_2026-06-30T04-46-31-678Z.json",
    "backups/readinghistories_2026-06-30T04-46-31-678Z.json",
    "backups/users_2026-06-30T04-46-31-678Z.json"
)

foreach ($f in $filesToDelete) {
    if (Test-Path $f) {
        git rm -r --cached --ignore-unmatch $f
        Remove-Item -Force -Recurse $f -ErrorAction SilentlyContinue
        Write-Output "Deleted $f"
    }
}
